# Generated by Django 4.2.9 on 2024-01-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abt', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('ph', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='projectPics')),
                ('p_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
