# Generated by Django 4.2.9 on 2024-01-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_about_education_projects_alter_links_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='abt',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='desc',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='education',
            name='desc',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='place',
            field=models.CharField(max_length=250),
        ),
    ]
