# Generated by Django 4.2.9 on 2024-01-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_experience_skills_alter_about_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='logo',
            field=models.CharField(max_length=120),
        ),
    ]
