# Generated by Django 4.2.9 on 2024-01-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_alter_skills_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=400)),
            ],
        ),
    ]
